jhudsl/ottrpal

R/set_knitr_image_path.R

I manually copied files to resources and then then worked for Leanpub. Did not get to test this function though... but easy fix if there is a problem with this

it appears that we do need to add resources to the image paths from my experience

---

R/bookdown_to_leanpub.R

The setwd() bits are throwing off the `leanbuild::bookdown_to_leanpub()` function when I attempt to call it from outside of R like: 
```
Rscript -e "leanbuild::bookdown_to_leanpub()" 
```
This makes this error: 
```
Error in bookdown::render_book(input = input, output_format = output_format) : 
object 'input' not found
Calls: <Anonymous> -> <Anonymous> -> <Anonymous> -> resolve -> basename
Error in setwd(owd) : object 'owd' not found
```
An example: https://github.com/jhudsl/ITCR_Documentation_and_Usability_Leanpub/runs/3423258226?check_suite_focus=true
It doesn't appear to be serving a function and `setwd()` is dicey sometimes anyway so I tried deleting it and running the command without it and it works fine. 
I may find out later why this chunk was needed but I guess I'll cross that …

Get rid of setwd() bits

---

.github/workflows/render-leanpub.yml
.github/workflows/update-leanpub.yml
DESCRIPTION
R/bookdown_to_leanpub.R
R/replace_html.R
man/bookdown_to_leanpub.Rd

This should fix this problem: https://github.com/jhudsl/leanbuild/pull/14#issuecomment-907156993
If all goes well, this should close #13 and close #17 
There were some commas missing in the `build_images()` function and I'm adding a new check which checks out the files from https://github.com/jhudsl/DaSL_Course_Template_Leanpub and runs the latest leanbuild changes there.

Add commas and gha check

---

DESCRIPTION
R/footnotes.R
R/replace_html.R

The sequel to #23 
This is working well! I added two functions which do the work and I incorporated it to run with the `bookdown_to_leanpub()` function. 
The footnote looks like: 
Which links you to a page like this: 
I think we may find we need to adjust this as it is used. I mainly made this for my use case while trying to write it guessing about other use cases but ¯\_(ツ)_/¯

Add footnote conversion: take 2

---

.github/workflows/update-leanpub.yml
DESCRIPTION

The GITHUB_REF variable is different if something is triggered by a PR or a merge. I copied the code for the PR triggered one to create this merging triggered one and that's why its broken (I'm pretty sure). 
It can't find the leanbuild folder I have it copy because GITHUB_REF is wrong and hence the url is wrong. 
Unfortunately I will need to merge this to test if it actually fixes it.

Try to fix GHA for filing PRs with leanbuild updates

---

DESCRIPTION
R/coursera.R

Closes #53 Just downloads the toc_close.css file if it doesn't exist. This file should be the same no matter what so makes sense to just add it to extData and have it download if its needed.

Add toc_close.css download

---

R/bookdown_to_leanpub.R

Background issues to this ongoing problem: #7 and #48 
Basically you need a certain version of pandoc (greater than 2.11) to render citations properly. If you don't have greater than that before leanbuild would just break. Now I just have it give you a warning that the citations won't build but it will continue. 
Also had my logic had the syntax incorrect so I had to fix that so that the question would be asked properly. Didn't realize in this particular instance numbers aren't actually treated like numbers in R. rmarkdown::pandoc_version() gives you a  `numeric_version` which is different than a number. TIL.

Citeproc Strikes Back: Add warning and fix syntax

---

R/replace_html.R

To fix issues with:
1) images not being full size
2) videos not being centered
3) some images not being centered
4) an extra period after images/videos
I think changing the `).`  to `)` in the `paste0` functions for adding the links to videos and images in R/replace_html.R should fix this.

I think this will remove the periods we need to get rid of

---

R/replace_html.R

This should close #63 
Is it the most elegant solution? No. But it works and it's simple.

Get rid of pesky comma on image specs

---

.Rbuildignore
.gitignore
R/aaa_utils.R
R/bookdown_to_leanpub.R

This will close #68 
I also added in a message that tells people what to look for after leanbuild finishes running.

Add space before feedback linee

---

R/bookdown_to_leanpub.R

Modifying the bookdown_to_leanpub code to copy quizzes
#79

potential fix to copy quizzes to manuscript dir

---

R/bookdown_to_leanpub.R

This is the sequel to #80 because I reviewed it too quickly and it didn't copy the quizzes. :sad: 
But now it does. I changed it to take the quiz_dir argument that a user specifies in the `bookdown_to_leanpub()` main function so it should inherit whatever that value is. Also added a message for if that directory isn't found.

Fix copy_quizzes to use `quiz_dir`

---

R/bookdown_to_leanpub.R

There's a small glitch in the `bookdown_to_book_txt()` function. It wasn't replacing the `.Rmd` with the `.md` suffixes. This fix makes sure it does do that so that those files show up in Leanpub.

Fix bookdown_to_book_txt

---

R/bookdown_to_leanpub.R
R/set_up.R
man/bookdown_to_book_txt.Rd
man/bookdown_to_embed_leanpub.Rd
man/bookdown_to_leanpub.Rd
man/get_chapters.Rd
man/set_up_leanpub.Rd

There were some extra files being transferred and things that didn't work ideally so this is me neatening it up.

Improve Book_txt handling

---

R/bookdown_to_leanpub.R
man/bookdown_to_embed_leanpub.Rd
man/make_embed_markdown.Rd

The new embed renderer also needs the capability to add footer_text for survey's and etc.

Add footer_text functionality to ottr::bookdown_to_embed_leanpub

---

R/bookdown_to_leanpub.R
R/set_up.R

Originally, I had set this up so you could say `quiz_dir = NULL` and the quiz parts would be skipped, but there was one part that was missing that handling.

Update quiz handling

---

R/quiz.R

https://github.com/datatrail-jhu/DataTrail_Quizzes/actions/runs/3605669950/jobs/6076290643
Leanpub quiz checks are failing because fill-in-the-blank questions that use regex (e.g., the second quiz [here](https://github.com/datatrail-jhu/DataTrail_Quizzes/blob/main/quizzes/01_forming_questions_01_data_science_process_quiz.md)) are not considered "correct answers" by the ottrpal check. the `parse_quiz_df` function looks only for a `uppercase)` pattern, not the `!` pattern, which should be fine according to markua docs.
Accommodate correct fill in the blank questions that start with `!` . Basically, looks for `C)` OR `!` to start the answer.

Accommodate `!` to start questions

---

R/coursera.R

Attempting a solution for https://github.com/jhudsl/OTTR_Template/issues/536. to accommodate:
```
bookdown::gitbook:
css: [assets/style.css, assets/AnVIL_style/anvil.css]
```
If multiple css files are provided in `_output.yml`, this now loops through and makes a "mega css" to proceed. 
Would appreciate if others can test/gut check this!

Accommodate multiple css

---

R/coursera.R

Ran into the issue of calling `ottrpal::render_without_toc` which depends on `ottrpal::bookdown_path` and getting an inscrutable message in github actions. Basically, it's not finding the path.
Going to do a quick test and make sure this works.

Resolve dependency on self

---

R/gs_png.R

While working on the Quarto version of OTTR, I noticed that the `include_slide()` function was downloading a Google Slide deck as a PPTX file with `get_gs_pptx(url)`.
After investigation, I realized that this was unnecessary as the line below, `outfile <- gs_png_download(url, output_dir, overwrite = overwrite)` was sufficient to download the individual slide from Google Slides as a PNG file and the next line, 
`knitr::include_graphics(outfile, ...)` embeds the PNG file in the document.

Remove line `get_gs_pptx(url)` from `include_slide()`

---

R/bookdown_to_leanpub.R

It shouldn't matter if the html page is local or not so making this more clear and hopefully less buggy! 🐛

Clean up the html_page argument in get_chapters()

---

R/get_data.R
R/url-check.R
tests/testthat/test-check-urls.R

This is for #152 And tests are added here!

Functionalize URL checker

---

tests/testthat/test-quarto_leanpub_prep.R

These tests are parallel to the Rmd rendering ones. We just want to make sure this works for Quarto too. 
Copied the tests from test-rmd_leanpub_prep.R and adjusted accordingly 
Part of #130

Quarto rendering tests
